
//////////////////////instant inbox resher using event listener starts here//////////////////////////
var zoulou = 0 //  generated by PHP
function addnumbernotif(){
	
	var count2 = $('#notifcount');
    var current = parseInt( count2.text() );
    current++;
    count2.text(current);
	//alert(current);
	  
    }
	
//this is the function processUpdate
var Update = function( answer ) 
{
	//alert('inbox checkpoint1 inbox');

    if ( zoulou != answer ) 
    {
        //replace_current_data_with_new_via_ajax();
		  //alert('its inbox last date=');
		// alert(answer);
        zoulou = answer;
		addnumbernotif ();
		
    }
	else{	
	// ('nothing');
	 //(zoulou);
	}
}
//  Compare our current Generate ID against that of the server
var checknotif = function()
{
	// alert('we are getting it');
		page2 = "notification/notiflisten.php";
    serverPoll2 = setInterval( function()
    {
        $.get(page2, 
          // { lastupdate: 1 }, this is a parameter to send to the php file
          Update, 'html');
    }, 2000 )
};

//  Check for updates onload of the document

$(document).ready( checknotif);