
			//this script auto refresh the date of lastseen of the logged users
 setInterval (function()
 {
  // a function which will load data from other file after x seconds
      $("#overtime").load("activeusers/overtime.php").fadeIn("slow");
// refresh div after  secs  
},1000);  

           //this script auto refresh the list of active users
 
////////////////instant discussion using event listener starts here/////////////////////////////

var x = 0 //  generated by PHP
function refreshdivmessage(){
	// alert ('checkpoint3');
	// alert (attributes);
	// alert(page);
	// alert (href);
	// alert ('I am about to refresh ');
  $(".activelist").load("activeusers/listofactiveusers.php")		// alert(attributes);
		// alert('refreshed');
    }
	var response;
//this is the function processUpdate
var processUpdateMessage = function( response ) 
{  
// alert('message checkpoint2');
// alert (response);
// alert(x);
    if ( x != response ) 
    {
        //replace_current_data_with_new_via_ajax();
		 // alert(attributes);
		 // alert(x);
		 // alert('last message date in this conversation=');
		 // alert('will be refreshed');
		 // alert(response);
		 response = response;
        x = response;
		refreshdivmessage ();
			
    }
	else{	
	// alert('nothing in message alert x =');
	// alert(x);
	}
}
//  Compare our href Generate ID against that of the server
var checkUpdates = function()
{
	// alert ('checkpoint1');
	// alert (href);

		z = "http://localhost/project/ALUi%20Dynamic/ALUi%20Dynamic/activeusers/listeneractiveusers.php";
						
				// clearInterval(serverPollMessage);
    serverPollMessage = setInterval( function()
    {
		// alert(href);
		// alert(z);
        $.get(z, 
          // { lastupdate: 1 }, this is a parameter to send to the php file
          processUpdateMessage, 'html');
    }, 3000 )
};
var serverPollMessage;
//  Check for updates onload of the document
//////////////////////instant discussion using event listener ends here//////////////////////////

$(document).ready (checkUpdates);
 
        
       // NEW this load html inside div 
		$(document).ready(function(){
			$("nave").load('activeusers/listofactiveusers.php');
		}); 
		// NEW this load html inside div 
// $(".linkfloat").click(function(){
	// var page = $(this).attr('href');
	// $("#floatchat").load(page);
	// return false;
// });
		// $(document).ready(function(){
			// $("#floatchat").load('privatetalk/messageprint.php');
		// });
function createbox(page){       
// document.getElementById("floatchat").innerHTML = page;      
				 $('#floatchat').append(
				 '<div class = "minitextbox"><object  class = "minitext" type="text/html" data="'+page+'" ><form action ="" class = "miniform" ></object><input type = text/ class = "minitextarea"></form></div>'
				 );
                   }
			// $("#linkfloat").click(function(){
    // var x = document.getElementById("linkfloat").getAttribute("href"); 
    // document.getElementById("floatchat").innerHTML = x;
// return false;
	// })
		// this load any a inside that div
	

