var s;
$('#stop').click(function(){
  $(this).data('clicked', true);
});
	if($('#stop').data('clicked')) {
    s = true;
	alert (s);
} else {
    s = false;
}	

	// clearInterval(serverPollMessage);	
		//live content effect onclick on inbox

// refresh messageprint only after database changes//

////////////////instant discussion using event listener starts here/////////////////////////////
var x = 0 //  generated by PHP
function refreshdivmessage(){
	// alert ('checkpoint3');
	// alert (attributes);
	var z = "messageprint.php?";
        $('#messageframe').load(z+attributes);
		// alert(attributes);
    }
	var response;
//this is the function processUpdate
var processUpdateMessage = function( response ) 
{  
// alert('message checkpoint2');
// alert (response);
    if ( x != response ) 
    {
        //replace_current_data_with_new_via_ajax();
		 // alert(attributes);
		 // alert(x);
		 // alert('last message date in this conversation=');
		 // alert(response);
		 response = response;
        x = response;
		refreshdivmessage ();
			
    }
	else{	
	// alert('nothing in message alert x =');
	// alert(x);
	}
}
//  Compare our href Generate ID against that of the server
var checkUpdates = function()
{
	// alert ('checkpoint1');
	// alert (href);

		var href = $(this).attr('href');
		z = "listen.php?";
						
		if (s = true) {
s = false;
			};

	clearInterval(serverPollMessage);
				// clearInterval(serverPollMessage);
    serverPollMessage = setInterval( function()
    {
        $.get(z+href, 
          // { lastupdate: 1 }, this is a parameter to send to the php file
          processUpdateMessage, 'html');
    }, 2000 )
};
var serverPollMessage;
//  Check for updates onload of the document

	$(document).on('click','.inbox', checkUpdates );


//function that changes the content of a textarea on click of a div
function changeText(value) {
     document.getElementById('newmessage').value = value;   
}
//////////////////////instant discussion using event listener ends here//////////////////////////

			// NEW this script auto refresh the date of lastseen of the logged users
 // setInterval (function()
 // {
  // a function which will load data from other file after x seconds
      // $("#messageframe").load('messageprint.php').fadeIn("slow");
// refresh div after  secs  
// },3000);  
$(document).on('click','.inbox', function(){
 attributes = $(this).attr('href');
 x = 2;
	var prefix = "messageprint.php?";
	$("#messageframe").load(prefix+attributes);
// alert('should be once per click');
}
);

//you'll be proud reading these code that you spend energy time, emotion. today on Monday 09/05/16 seminal reading 18:26, I am so hungry, Mauritius, Piment Banane, the housing administrator, I love myself, so much//