<html>
<head>
<meta http-equiv="refreshes" content="">
<script src="../jquery.min.js"></script>
</head>
<div id = "messageprint">
<?php
// echo ('apple will disapear');
// if (isset($_GET['tablemessage'])){
//$tablemessage = $_GET['tablemessage'];
$connection = $_GET['contact'];
// }
// echo '<br> checkpoint1';
require ('messageprintlive.php');
?>
</div>
<script>



	// clearInterval(serverPollMessage);	
		//live content effect onclick on inbox

// refresh messageprint only after database changes//

////////////////instant discussion using event listener starts here/////////////////////////////

var x = 0 //  generated by PHP
function refreshdivmessage(){
	// alert ('checkpoint3');
	// alert (attributes);
	var page = "messageprintlive.php?tablemessage=";
	contact = "<?php echo '&contact='.$connection.''; ?>";
	// alert(page);
	// alert (href);
	// alert ('I am about to refresh ');
$("#messageprint").load(page+href+contact);
		// alert(attributes);
		// alert('refreshed');
    }
	var response;
//this is the function processUpdate
var processUpdateMessage = function( response ) 
{  
// alert('message checkpoint2');
// alert (response);
// alert(x);
    if ( x != response ) 
    {
        //replace_current_data_with_new_via_ajax();
		 // alert(attributes);
		 // alert(x);
		 // alert('last message date in this conversation=');
		 // alert('will be refreshed');
		 // alert(response);
		 response = response;
        x = response;
		refreshdivmessage ();
			
    }
	else{	
	// alert('nothing in message alert x =');
	// alert(x);
	}
}
//  Compare our href Generate ID against that of the server
var checkUpdates = function()
{
	// alert ('checkpoint1');
	// alert (href);

		href = "<?php echo $tablemessage; ?>";
		z = "listen.php?tablemessage=";
		// alert(z+href);
						
				// clearInterval(serverPollMessage);
    serverPollMessage = setInterval( function()
    {
		// alert(href);
        $.get(z+href, 
          // { lastupdate: 1 }, this is a parameter to send to the php file
          processUpdateMessage, 'html');
    }, 2000 )
};
var serverPollMessage;
//  Check for updates onload of the document
//////////////////////instant discussion using event listener ends here//////////////////////////

$(document).ready (checkUpdates);

//you'll be proud reading these code that you spend energy time, emotion. today on Monday 09/05/16 seminal reading 18:26, I am so hungry, Mauritius, Piment Banane, the housing administrator, I love myself, so much//
</script>
   </html>
